### ISSUE TITLE
[STUDY] Testes Unitários ReactJs

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#121]
### Descrição:
Estudar testes unitários de react, sem o uso de snapshots.

### Comentários
Documentação do enzyme disponível no [link.](https://airbnb.io/enzyme/)

**Comment by MatheusEstanislau** [comment]
Realizado estudos sobre testes unitários utilizando o utilitário de testes javascript Enzyme

**Comment by RCristyan** [comment]
Realizado estudo sobre Shallow Rendering do Enzyme, disponível em https://airbnb.io/enzyme/docs/api/shallow.html

**Comment by lukassxp** [comment]
Como estão os estudos dos testes? Estou com a impressão de que vcs estão negligenciando a issue. @MatheusEstanislau @RCristyan @jpcirqueira @MoacirMSJ @lucasA27

**Comment by lukassxp** [comment]
> Como estão os estudos dos testes? Estou com a impressão de que vcs estão negligenciando a issue. @MatheusEstanislau @RCristyan @jpcirqueira @MoacirMSJ @lucasA27

Como andam os estudos?

**Comment by jpcirqueira** [comment]
como já foi dito, estamos com dificuldades em relação aos teste. Durante a aula pedimos auxilio da professora e ela nos indicou um monitor, entramos em contato para conseguir ajuda.
