### ISSUE TITLE
[US15] "Linkar" Monitoria ao Perfil do Usuário que a Criou

### ISSUE THREAD

**Issue by lukassxp** [fga-eps-mds/2019.1-MaisMonitoria#125]
### Descrição:
<p align="justify">
Deve ser "linkado" as monitorias criadas(oferecidas) por um usuário ao seu perfil. Note que já existe em cada monitoria uma referência para o usuário que a criou, no entanto o intuito da issue é disponibilizar junto ao perfil do usuário uma lista com a referência para todas as monitorias criadas(oferecidas) por ele, visando evitar uma query custosa ao banco de dados toda vez que o perfil de um usuário for acessado.  
</p> 

### Tarefas

- [x] Criar método POST personalizado no microsserviço de monitorias para a criação de monitorias, este método também deve ser responsável por adicionar ao perfil do usuário a monitoria criada. A lógica de adição ao perfil não necessariamente precisa ficar retida a este método, ficando a gosto de quem implementar criar ou não métodos auxiliares.
- [x] Ajustar método POST de redirecionamento da criação de uma monitoria na GATEWAY.
- [x] Ajustar tela de perfil no front-end para que sejam exibidas as monitorias oferecidas pelo usuário na tela do seu perfil.
- [x] Realizar testes unitários de todo o código produzido durante a resolução da issue.
 
### Comentários
<p align="justify">
Caso haja dificuldade durante a realização da implementação ou dos testes unitários do método POST personalizado, tomar como exemplo os métodos personalizados e testes unitários  na que estão implementados na GATEWAY. 
</p>

**Comment by jpcirqueira** [comment]
Foi sobrescrito o método POST da classe monitoria.

**Comment by lucasA27** [comment]
Foram realizados os testes unitários no api monitoria, visando manter a cobertura em 100%

**Comment by jpcirqueira** [comment]
as tasks foram finalizados e os pull requests foram abertos e estão aguardando revisão.

**Comment by lukassxp** [comment]
A equipe de EPS decidiu relativizar a ultima task exigindo testes unitários apenas no serviço de monitorias, pois para testar a gateway e o front seriam necessários conhecimentos que a equipe ainda não possui.

**Comment by caiooliv** [comment]
Os critérios de aceitação foram cumpridos, assim foi mergado os PR's nos respectivos repositórios e a issue será fechada.
