### ISSUE TITLE
[US16] Esqueceu Senha

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#127]
### Descrição:
O usuário deve conseguir redefinir a senha, se possuir os dados corretos, a partir do link de "esqueceu senha" encontrado na tela de login.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x]  Criação do método para enviar email de redefinição de senha.
- [x] Feedback ao usuário (Email incorreto, confirmação de redefinição de senha, falha na redefinição de senha).

### Comentários
Link para a [documentação sobre gestão de usuários do firebase.](https://firebase.google.com/docs/auth/web/manage-users?hl=pt-br)

**Comment by lucasA27** [comment]
Foi feito o metodo para enviar o email de redefinição de senha como sugerido na documentação do firabase, assim como o feedback da entrada de email

Exemplo de email:

![Email](https://user-images.githubusercontent.com/44438409/57723618-63368980-765f-11e9-9d45-aa20f8b7dfbd.png)

**Comment by lucasA27** [comment]
Foi preterido não fazer a redefinição de senha através do nosso App, e sim pela própria url do Firebase. Essa decisão foi tomada depois de vários testes, e assim seria mais vantajoso. Pelo método que estava sendo utilizado apareceu alguns erros. Para que seja possível definir a senha de um usuário, é preciso que ele tenha feito login recentemente, ou reautentica-lo, o que não seria tão vantajoso para nós. Documentação base: https://firebase.google.com/docs/auth/web/manage-users?hl=pt-br

**Comment by LucasSiqz** [comment]
Revisado e aprovado apesar de ser necessário dois cliques no botão para enviar o email.
