### ISSUE TITLE
[REFACTOR] Cards de Monitorias

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#128]
### Motivo de refatoração:
Os cards de apresentação das monitorias devem ser refatorados para que tenham um visual mais atraente e disponibilizar informações mais relevantes para o usuário.

### Tópicos de aceitação:
- [x] Página exclusiva com apresentação informações dos cards.
- [x] Reestilização do visual do card no feed.
- [x] Alteração nos métodos de distribuição de dados no backend.

**Comment by lukassxp** [comment]
Durante a realização da issue, surgiu a necessidade de incluir a opção para que o usuário possa escolher uma foto de perfil, pois o novo design escolhido para os cards tem um espaço reservado para a foto de perfil do monitor, então visando deixar o card totalmente funcional ao fim da issue foi adiantada a implementação desta funcionalidade.

**Comment by caiooliv** [comment]
Foram feitas as reestilizações nos cards, no feed agora elas contam com a foto do perfil do monitor e com mais informações sobre as monitorias. Ao clicar em uma monitoria é redirecionado para tela com mais informações sobre a mesma.

**Comment by caiooliv** [comment]
Foi feita a página exclusiva para cada monitoria, a partir do feed o usuário pode acessar os detalhes da monitoria clicando no card disponível no feed.
