### ISSUE TITLE
[US17] Feedback Para Usuários

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#129]
### Descrição:
Deve haver feedback para os usuários de acordo com o resultado da ação tomada pelo mesmo, como de sucesso ou falha da ação.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Motivos de falha do login.
- [x] Motivos de falha de registro
- [x] Mensagem de sucesso de registro
- [x] Mensagem de sucesso de criação de monitoria
- [x] Motivos de falha da criação de monitoria
- [x] Mensagem de sucesso de edição do perfil
- [x] Motivos de falha  de edição do perfil

 
### Comentários
Link para [lista de erros de autenticação do firebase](https://firebase.google.com/docs/auth/admin/errors?hl=pt-br)

**Comment by MatheusEstanislau** [comment]
Nos motivos de falha do login, tivemos que alterar apenas as mensagens de textos exibidas para o usuário.

**Comment by jpcirqueira** [comment]
todas as task foram concluídas, porem alguns ajustes visuais nas telas ainda estão pendentes

**Comment by caiooliv** [comment]
Foi feito a revisão do PR e houve a necessidade de refatorações na parte visual.

**Comment by MatheusEstanislau** [comment]
Após o envio do Pull Request, foram solicitadas mudanças visuais no feedback para os usuários, tais mudanças já foram entregues.
