### ISSUE TITLE
[BUG] Botão de Login

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-MaisMonitoria#132]
### **Descreva o bug**
Ao iniciar o uso na aplicação, o usuário para realizar login atualmente necessita clicar várias vezes para logar.

### **Para reproduzir o bug**
Passos para reproduzir-lo:
1. Vá para tela de login.
2.  Insira email e senha válidos.
3. Clique no botão com o nome "Login".
4. Veja o erro.

### **Comportamento esperado**
Deve necessitar apenas um clique no botão para que o login seja realizado.

###  **Screenshots**
![image](https://user-images.githubusercontent.com/23382026/58026520-0d456400-7aed-11e9-8c69-da58fc4c5e0d.png)

### **Desktop (complete as seguintes informações):**
- OS: ubuntu 16.04 LTS
- Browser: Chrome
- Versão: 65.0.3325.162 (Versão oficial) 64 bits

**Comment by RCristyan** [comment]
O problema era causado por uma utilização incorreta das rotas, porém já foi solucionado e agora o usuário consegue fazer login com apenas 1 clique
