### ISSUE TITLE
[BUG] Indicador da AppBar 

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-MaisMonitoria#134]
### **Descreva o bug**
Ao realizar alguma ação, como de editar perfil o indicador da appbar seleciona de forma errada a indicação da tela.

### **Para reproduzir o bug**
Passos para reproduzir-lo:
1. Faça login.
2. Acesse a tela de perfil.
3. Clique em "Editar perfil".
4. Faça a edição.
5. Veja o erro.

### **Comportamento esperado**
Deve ou voltar para a tela de perfil, ou deve indicar de forma correta na appbar.

###  **Screenshots**
![image](https://user-images.githubusercontent.com/23382026/58027860-ee949c80-7aef-11e9-8c45-5b27be95533a.png)

### **Desktop (complete as seguintes informações):**
- OS: ubuntu 16.04 LTS
- Browser: Chrome
- Versão: 65.0.3325.162 (Versão oficial) 64 bits

**Comment by lucasA27** [comment]
A AppBar foi retirada das rotas e adicionadas nas componentes que ela compõe. Seu indicador foi passado por props e seu valor colocado na sua respectiva componente.

**Comment by LucasSiqz** [comment]
Solução adequada, e além da correção foi desabilitado o botão para acesso a tela de ranking que não foi implementada.
