### ISSUE TITLE
[US18] Autenticação de Rotas

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#135]
### Descrição:
Atualmente no mais monitoria, os usuários podem acessar qualquer parte da aplicação sem que haja uma verificação se o usuário possui a permissão para tal ação, além de que não há um botão de logout para que o usuário possa sair da sua conta na aplicação.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Funcionalidade de logout.
- [x] Autenticação de rotas.
- [x] Redirecionamento para tela de login para usuário sem autenticação.
 
### Comentários
Link para a [documentação do react router](https://reacttraining.com/react-router/web/guides/quick-start)

**Comment by lucasA27** [comment]
Foram feitas as autenticações através do firebase nas rotas das telas as quais o usuário não pode acessar sem estar logado, sendo redirecionados para tela de login.

**Comment by jpcirqueira** [comment]
foi adicionado uma funcionalidade de logout, através de um botão na Appbar e assim o usuário é redirecionado a pagina de login.

![Captura de tela de 2019-05-24 16-50-15](https://user-images.githubusercontent.com/31708472/58353150-20856600-7e44-11e9-94fd-ce31f68b83c2.png)

**Comment by caiooliv** [comment]
Agora usuários não autenticados não podem acessar as páginas diretamente pela URL, somente se estiverem logados com suas contas, além do botão de logout que redireciona o usuário para a página de login caso o usuário faça o logout.
