### ISSUE TITLE
[US19] Comunicação Entre Monitor e Aluno

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#136]
### Descrição:
Atualmente não há meios do aluno se comunicar com o monitor, apesar do cadastro possuir o campo de telegram essa informação não é utilizada para fazer a comunicação e nem é persistida no banco de dados.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] O telegram do usuário deve ser persistido na API
- [x] Deve haver um link para iniciar a conversa com o monitor no telegram

 
### Comentários
Link exemplo de [como iniciar char no telegram](https://www.quora.com/How-can-I-share-my-Telegram-link)
Link para [Documentação da API do telegram](https://core.telegram.org/api)

**Comment by MatheusEstanislau** [comment]
Inicialmente foi realizada a persistência do telegram do usuário na ApiMonitoria, logo após foram realizadas modificações nas validações tanto do registro quanto da edição do perfil do usuário. Com o intuito da criação de um link para redirecionar para o telegram do monitor foi necessário utilizar o método replace string para retirar o caractere '@'  e concatenar com 'https://t.me/'  disponibilizado pelo telegram.

**Comment by caiooliv** [comment]
Agora é possível iniciar uma conversa no telegram com o monitor, a partir do +monitoria, assim os critérios de aceitação foram cumpridos e a issue será fechada.
