### ISSUE TITLE
[TS17] Deploy Contínuo 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#138]
### Descrição:
Atualmente o deploy do sistema não é contínuo, assim é necessário um trabalho manual, que pode ser eliminado, trazendo  benefícios para equipe. Para isso é necessário a consolidação das etapas de build, testes e deploy no travis.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Deploy contínuo para ambiente de homologação.

**Comment by matheus-rn** [comment]
Fazer o deploy contínuo utilizando o travis é um pouco mais complicado do que se fosse feito no GitLab CI. Fazer o Upgrade do serviço no Rancher via api utilizando o cURL, gerou algumas dificuldades. Uma das alternativas é criar um script que faça essa tarefa, isso será a meta do DevOps nos próximos 2 dias.

**Comment by matheus-rn** [comment]
Fiz o script que acessa a api do rancher e faz o deploy contínuo. O travis vai rodar esse script python.

**Comment by matheus-rn** [comment]
O deploy contínuo foi implementado.
