### ISSUE TITLE
[DOC] Teste de Usabilidade

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#139]
### Descrição:
Com o passar do projeto foi visto a necessidade de testes de usabilidade por outros usuários além dos membros da equipe, para que o produto atinja uma qualidade melhor e providencie uma melhor usabilidade para os usuários do produto

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [ ] Criar documento dos testes de usabilidade.

**Comment by LucasSiqz** [comment]
Foi feito um teste de usabilidade com um aluno de ciência da computação da universidade de brasília.

informações a serem documentadas:

Nome: Alison de Miranda
Contexto: Aluno da Universidade de Brasilia, curso de ciencia da computação.
Mediador: Lucas Siqueira

1 - Cadastrar um usuário - conseguiu realizar a ação, sem dificuldades.
2 - Fazer login - conseguiu realizar a ação, sem dificuldades.
3 - Cadastrar uma monitoria - conseguiu realizar a ação, sem dificuldades.
4 - Pesquisar uma monitoria - conseguiu realizar a ação, sem dificuldades.
5 - Acessar e navegar na tela de perfil - conseguiu realizar a ação, sem dificuldades.  
6 - Editar uma monitoria - conseguiu realizar a ação, porém não executou os passos esperados
invés de acessar a sua monitoria pela tela de perfil, alterou-a pelo feed.
7 - Editar perfil - Não conseguiu realizar a ação, ao clicar em confirmar a ação o requisição
não foi concluída e ficou o loading spinner infinito na tela.
8 - Abrir uma conversa com o monitor - conseguiu realizar a ação, sem dificuldades.
9 -  Logout - Concluiu a ação, com certa dificuldade, inicialmente não foi intuitivo que o botão
de logout é apenas na tela de perfil.

Feedback
1 - Achei que deveria deixar claro se a foto é um campo obrigatorio ou não.
2 - Nenhuma sugestão
3 - Já vir com um campo selecionavél as materias, definir politicas de uso de 
descrição e dar uma texto transparente de fundo como exemplo.
4 - Achei a tela vazia, poderia adicionar uma lupa informando pelo que eu posso pesquisar
ao acessar a tela já deixar o campo selecionado e o teclado do celular disponível para uso.
5 - Trocaria o texto de " a ministrar " para "ministrando"
6 - Visual diferente no campo de descrição em relação ao campo de criar uma monitoria.
7 - Verificar o erro e corrigi-lo, vir com o campo de curso preenchido, e alterar o botão de
"Escolher foto" para "Alterar foto".
8 - Ao clicar na foto do monitor, levar para a tela de perfil do mesmo e não expandir 
uma monitoria.
9 - Nenhuma sugestão.

**Comment by LucasSiqz** [comment]
O erro na ação de editar perfil ocorreu no caso em que o usuário não edita a sua foto, quando a foto é edita a edição a concluída da devida forma, o bug será cadastrado e consertado assim que possível.

**Comment by LucasSiqz** [comment]
informações a serem documentadas:

Nome: Lucas Lermen
Contexto: Aluno da Universidade de Brasilia, curso de Engenharia de Software.
Mediador: Lucas Siqueira

Ações a serem realizadas:

1 - Cadastrar um usuário - Não conseguiu realizar a ação na 1 tentativa, devido ao um erro na regex do nome.
2 - Fazer login - Conseguiu realizar sem dificuldades.
3 - Cadastrar uma monitoria - Conseguiu realizar a ação sem dificuldades.
4 - Pesquisar uma monitoria - Conseguiu realizar a ação sem dificuldades.
5 - Acessar e navegar na tela de perfil - Conseguiu realizar a ação sem dificuldades.
6 - Editar uma monitoria - Conseguiu realizar a ação sem dificuldades.
7 - Editar perfil - Conseguiu realizar sem dificuldades, porém a aplicação não correspondeu como esperado, a foto não foi devidamente editada.
8 - Abrir uma conversa com o monitor - Conseguiu realizar a ação sem dificuldades.
9 - Favoritar e acessar a monitoria favoritada - Conseguiu realizar a ação com certa dificuldade.
10 - Logout - Conseguiu realizara a ação com certa dificuldade.

Feedback após teste:

1 - Não apresentou um feedback que está carregando a requisição.
2 - Nenhuma.
3 - Nenhuma.
4 - Nenhuma.
5 - Não há necessidade da repetição das fotos do monitor na a aba a ministrar.
6 - Possibilitar o redirecionamento para tela de edição a partir dos cards.
7 - Não apareceu o curso anterior preenchido, a foto não foi devidamente alterada e poderia ter uma opção de alterar a foto sem ter que remover primeiro.
8 - Abrir uma nova pagina para iniciar conversa sem que feche o +monitoria.
9 - Acesso as monitorias curtidas a partir do feed.
10 - Poder fazer logout também pelo feed.

**Comment by LucasSiqz** [comment]
Foi feito um teste de usabilidade com um aluno de ciência da computação da universidade de brasília.

informações a serem documentadas:

Nome: Gabriela Moraes
Contexto: Aluna da Universidade de Brasilia, curso de Engenharia de Software.
Mediador: Lucas Siqueira

Ações a serem realizadas:

1 - Cadastrar um usuário - conseguiu concluir com certa dificuldade, escreveu uma senha fraca.
2 - Fazer login - conseguiu concluir a ação sem dificuldades.
3 - Cadastrar uma monitoria - conseguiu concluir a ação sem dificuldades.
4 - Pesquisar uma monitoria - conseguiu concluir sem dificuldades.
5 - Acessar e navegar na tela de perfil - conseguiu concluir sem dificuldades, porém aconteceu um comportamento inesperado, apareceu uma curtida na aba "curtidas" equivocada.
6 - Editar uma monitoria - conseguiu editar sem dificuldades.
7 - Editar perfil - conseguiu realizar a ação com certa dificuldade, pois estava na tela expandida de uma monitoria dela e clicou em editar.
8 - Abrir uma conversa com o monitor - conseguiu realizar com muita dificuldade, demorou para encontrar o botão para realizar a ação. 
9 - Favoritar e acessar a monitoria favoritada - conseguiu realizar sem dificuldades.
10 - Logout - conseguiu realizar sem dificuldades.

Feedback após teste:

1 - Posicionamento do feeback de erro e informar o motivo da senha estar fraca.
2 - Nenhum.
3 - Nenhum.
4 -Após realizar a pesquisa ao voltar poderia redirecionar para a tela anterior e não diretamente para o feed. 
5 - Nenhuma, apenas mostrar erradamente uma monitoria que eu não curti.
6 - A obrigatoriedade da edição do campo de descrição esta inconsistente com a criação da monitoria.
7 - Vir com o campo de curso preenchido, para alterar a foto poderia utilizar a imagem como o "botão".
8 - Nenhum.
9 - Nenhum.
10 - Mudar os 3 pontinhos para uma portinha de saída.

**Comment by caiooliv** [comment]
O documento do teste de usabilidade foi criado utilizando os testes realizados pelo @LucasSiqz , o documento se encontra na página de documentação do mais monitoria.
