### ISSUE TITLE
[TS18] Implantar no Backend Like/Favoritar Monitoria

### ISSUE THREAD

**Issue by lukassxp** [fga-eps-mds/2019.1-MaisMonitoria#140]
### Descrição:
Foi realizada uma readequação da parte do escopo do produto que será realizado durante a disciplina, durante essa readequação optamos por não implementar o sistema de solicitação de monitoria substituindo o mesmo por um sistema de Like/Favoritar monitoria devido a menor complexidade da implementação, além de esse novo sistema de Like/Favoritar resolver um outro problema que é fácil acesso a uma monitoria que o usuário possa ter se interessado. 

### Tarefas

- [x] Excluir a estrutura de solicitação e recibo de monitorias que havia sido previamente "implementada". (URLS, Models, atributos em outras Models, Views e Serializers)
- [x] Modelar estrutura de Like/Favoritar.
- [x] Atualizar diagrama de classes do microsserviço ApiMonitoria. 
- [x] Implantar modelagem proposta. (Models)
- [x] Implementar Views (GET, POST, DELETE), Serializers e Rotas(URLS).
- [x] Construir métodos de redirecionamento na ApiGateway.
 
### Comentários
Ficar atento pois não é necessário um método PUT e diferentemente dos outros registros um Like/Favoritar pode ser excluido, então necessita de um DELETE, é necessário atenção também no momento de implementar GET tendo em vista que juntamente com um Like/Favoritar será necessário devolver algumas informações do usuário que deu like/favoritou a monitoria relevantes no contexto. Por ultimo no momento do POST deve ser atualizada a lista de Likes/Favoritadas da monitoria visando economizar requisições e querys complexas ao banco de dados.

**Comment by MoacirMSJ** [comment]
Foi atualizada a estrutura do projeto, excluindo as classe Solicitantes e recibo, para adequar-se ao novo sistema de like. Adicionou-se ao projeto um app Like e foi modelada a estrutura da classe Like. Implementamos os métodos  CREATE e DESTROY na LikeViewSet. As novas rotas foram cadastradas, e  foram criadas as classes da serializer referente a classe Like.

**Comment by MoacirMSJ** [comment]
Foi efetuada a atualização do diagrama de classes(diagrama_0.3). Disponível em:[diagrama de classes](https://drive.google.com/drive/folders/18LNvrzrv8HmDT-B7FrIzIdmEz7rE-4uV).

**Comment by lukassxp** [comment]
**Relato da atividade:**

Durante a sprint o arquiteto(eu) se reuniu com um membros de MDS designado para a issue algumas vezes e primeiramente conversou sobre modelagem e banco de dados para que eles entendessem sobre oq se trata a issue, logo após foram passadas orientações pra se iniciar a atividade. A dinâmica da realização da atividade se deu da seguinte forma:

- O arquiteto orientou o MDS sobre oq excluir/limpar da antiga modelagem.
- O arquiteto propôs as alterações a serem realizadas.
- O arquiteto realizou pareamento com o membro de MDS para implantação das alterações nas classes, views, serializers e rotas.
- O arquiteto delegou ao MDS as demais tasks da issue, passando a realizar apenas revisão. (Métodos da Gateway e Atulizar diagrama de classes)

Houve uma reunião com a equipe de EPS onde o arquiteto apresentou a modelagem, foram sanadas algumas pequenas duvidas que restavam, após a apresentação foram aceitas as alterações.

**Obs:** 

Foi necessário a participação do arquiteto na implementação devido a falta de experiencia do membro de MDS com alguns recursos necessários para realizar a implementação.  

**A issue foi considerada concluída pela equipe de EPS!**
