### ISSUE TITLE
[US20] Like em Monitoria

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#143]
### Descrição:
É necessário a implementação do frontend para o sistema de like de monitorias.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Métodos de dar like em uma monitoria no card de monitoria.
- [x] Remoção da página de ranking pela página com os seus likes.
- [x] Lista de likes dentro do card de monitoria.

**Comment by MoacirMSJ** [comment]
Ao desenvolver o sistema de like encontramos dificuldade em limitar o múltiplo like criado pelo usuário (clicando 2 vezes rapidamente o usuário poderia efetuar vários likes na mesma monitoria).

**Comment by LucasSiqz** [comment]
A solução está de acordo, e foi implementada uma pagina com a listagem dos usuários que deram o like, que não estava descrito nos critérios da issue, sendo possível também acessar o perfil do usuário por essa tela.
