### ISSUE TITLE
[US22] Tela de Perfil

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#147]
### Descrição:
Deve ser refatorado o visual da página de perfil, para que o usuário tenha a sua disposição informações relevantes e com um visual agradável.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Formato da foto de perfil ajustado de acordo com o resto da aplicação.
- [x] Ajuste na fonte e formatação das informações do usuário ( ex: nome e curso)
- [x] Ajuste na tab de navegação das monitorias.
- [x] Adição das monitorias que receberam like.

**Comment by MoacirMSJ** [comment]
A composição da Tela de Perfil dificultou a passagem de informações da posição da seção da ProfileTab, então reestruturamos a ProfileTab passando as informações, requisitadas do Usuario, do componente Profile para a ProfileTab distribuindo assim as informações de suas monitorias e suas curtidas em cards de seções diferentes.
