### ISSUE TITLE
[US23] Refatorar feed

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#148]
### Descrição:
Atualmente os card de monitoria apresentado no feed aparecem em ordem de criação, o que foi criado primeiro aparece em primeiro e assim em diante, é necessário que o feed mostre as monitorias de acordo com as atualizações, a última criada será a primeira no feed. 

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Reordenação da ordem das monitorias no feed.

**Comment by MoacirMSJ** [comment]
Foi feita a inversão da ordem do queryset no Api Monitorias, retornando as monitorias em ordem decrescente a partir da data e hora de criação das monitorias.
