### ISSUE TITLE
[US24] Loading Spinners

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#149]
### Descrição:
Alguns processos dentro da aplicação necessitam de requisições às API's e isso pode demorar algum tempo, é necessário um feedback ao usuário de que aquela operação está sendo feita, para isso deve se usar os load spinners, já presente em algumas operações dentro da aplicação.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Adicionar spinner na tela de login.
- [x] Adicionar spinner na tela de registrar usuário.
- [x] Adicionar spinner na tela de edição de perfil.
- [x] Adicionar spinner na tela de atualização do feed.
- [x] Adicionar spinner na tela perfil.
- [x] Adicionar spinner na tela de card expandido

**Comment by RCristyan** [comment]
O que demandou mais tempo na conclusão dessa issue foi corrigir o posicionamento dos loading spinners nos componentes. Os spinners e as outras coisas da aplicação estavam em um mesmo grid, ou seja, mover a posição dos spinners também moveria a posição das outras coisas, o que seria errado. 

Para corrigir este problema eu alterei o posicionamento do grid externo com marginTop e marginLeft para organizar o spinner e, assim que o spinner parasse de ser renderizado, reverti as alterações no grid interno. Desta forma foi possível fazer o spinner ficar no local correto sem alterar a página.
