### ISSUE TITLE
[REFACTOR] Refatorar feedback do esqueceu senha

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#150]
### Motivo de refatoração:
Atualmente os feedbacks de ações dos usuários é feito por meio de "snackbars", exceto na página de esqueceu senha. Essa página deve ser refatorada para seguir os modelos atuais do projeto.

### Tópicos de aceitação:
- [x] Adição de snackbars no feedback da página de esqueceu senha

**Comment by jpcirqueira** [comment]
Foi refatorado o feedback de erro da página de esqueceu senha, foi posto um componente Snackbar para representar o erro, também foi adicionado um feedback de sucesso nesta pagina.
