### ISSUE TITLE
[US25] Página Não Econtrada

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#151]
### Descrição:
Atualmente na aplicação se o usuário entrar com uma URL inválida não há nenhum feedback para o usuário de que página não existe, necessário que  exista uma página mostrando o erro com botão de redirecionamento para a página inicial.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Tela com mensagem de erro.
- [x] Redirecionamento para a página inicial.

**Comment by lucasA27** [comment]
Foi configurado nas rotas com o React Router um caminho curinga com um asterisco ('*') e adicionado como o último caminho. Foi um componente NotFound para as paginas não encontradas e redirecionando o usuário para a tela de login.

**Comment by LucasSiqz** [comment]
Solução adequada ao problema.
