### ISSUE TITLE
[US26] Fotos de Perfil 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#152]
### Descrição:
No upload de imagem na hora de cadastrar o perfil e editar perfil, é necessário uma pré-visualização da foto escolhida e uma validação dos formatos e tamanhos da imagem.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Aceitar somente imagens '.png', '.jpeg'
- [x] Pré visualização das fotos 
- [x] Botão de exclusão da imagem para poder carregar novamente.

**Comment by RCristyan** [comment]
Tivemos alguns problemas para limitar os formatos de imagem que são aceitos, isso gerou um pequeno atraso no fechamento da issue. Porém todos os requisitos foram atendidos e as mudanças aguardam aprovação para serem incluídas na branch 'develop'

**Comment by caiooliv** [comment]
Agora é possível visualizar a foto que escolheu antes de finalizar o cadastro, além de poder remover a foto caso não o agrade, assim o cadastro se torna mais amigável para o usuário.
