### ISSUE TITLE
[REFACTOR] Refatorar Backlog

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#153]
### Descrição:
Após conversas com monitores das matérias foi visto a necessidade da refatoração do backlog.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Refatoração do documento de backlog
- [x] Refatoração no backlog do repositório.

**Comment by LucasSiqz** [comment]
Foi refatorado apenas o backlog que irá se adequar a disciplina em um novo documento, deixando disponível a versão anterior, também foi adicionada a justificativa para tal refatoração.

**Comment by LucasSiqz** [comment]
Ficaram 3 Épicos:

- EPIC01 - Sistema de monitorias
- EPIC02 - Contas de Usuário
- EPIC03 - Feedbacks

Não existe mais a notação de Feature, visto que nossas US's já estavam caracterizadas como Features.
