### ISSUE TITLE
[REFACTOR] Configuração dos Repositórios 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#154]
### Descrição:
Após discussão entre os membros da equipe e feedback dos orientadores viu-se a necessidade de uma refatoração dos repositórios para melhor andamento do projeto.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Método para subir todos os contêiner do projeto de uma vez.
- [x] Adicionar badges que faltam.
- [x] Folha de estilo na integração.
 
### Comentários
Links dos repositórios: 
[Docs](https://github.com/fga-eps-mds/2019.1-MaisMonitoria)
[FrontEnd](https://github.com/fga-eps-mds/2019.1-MaisMonitoria-FrontEnd)
[ApiMonitoria](https://github.com/fga-eps-mds/2019.1-MaisMonitoria-ApiMonitorias)
[Gateway](https://github.com/fga-eps-mds/2019.1-MaisMonitoria-api)

**Comment by lukassxp** [comment]
O que é necessário corrigir no readme dos repositórios além de adicionar os badges?

**Comment by caiooliv** [comment]
Na R1 houve pedidos de mudança na visão de produto dos readmes, a reclamação foi que está muito superficial o modo que está escrito.

**Comment by lukassxp** [comment]
> Na R1 houve pedidos de mudança na visão de produto dos readmes, a reclamação foi que está muito superficial o modo que está escrito.

Ok, no entanto eu acho que não cabe a essa issue realizar essas alterações, pois o intuito dela é tratar de questões de configuração. Acho adequado que esse critério de aceitação especifico seja retirado da issue.

**Comment by lukassxp** [comment]
Foi adicionada a verificação da folha de estilo ao pipeline de integração continua da API Gateway e da API Monitoria, no front-end não será realizada essa verificação por enquanto pois não achamos uma ferramenta que faça tais verificações para JS dentro do padrão que queremos. Também foram adicionados os badges que faltavam aos repositórios.
