### ISSUE TITLE
[US27] Tela de perfil do monitor

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#159]
### Descrição:
Ao clicar para ver os detalhes da monitoria há informações do monitor, porém não possui todas as informações do monitor, para melhor interação do aluno com monitor é necessário o redirecionamento para a página de perfil do monitor. 

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Criar página de perfil do monitor.
- [x] Redirecionamento da tela de monitoria para a do monitor
- [x] Método na Api Monitoria para trazer informações do monitor
- [x] Método na Api gateway para conseguir enviar e receber as informações da  Api monitoria.

**Comment by lucasA27** [comment]
Foi criada a tela de perfil do monitor, e feito o redirecionamento da tela de monitoria para a do monitor através do botão "ver perfil"(não é possível ver esse botão nas suas próprias monitorias). Também foi criado um método na Api Gateway para receber os dados da Api Monitoria.
Segue o print do método:
![image](https://user-images.githubusercontent.com/44438409/58921756-7c869f00-870e-11e9-97a4-f8cbb41bd22d.png)

**Comment by caiooliv** [comment]
Agora é possível ver a tela do monitor a partir de uma monitoria, cumprindo todos os critérios de aceitação a issue será fechada.
