### ISSUE TITLE
[DOC] Priorização

### ISSUE THREAD

**Issue by LucasSiqz** [fga-eps-mds/2019.1-MaisMonitoria#16]
### Descrição:
Vários requisitos foram elicitados para definir por onde começar a desenvolver, e para isso, é necessário priorizar os requisitos. As técnicas escolhidas foram Moscow e First Things First.

### Tópicos do documento

- [x] Introdução
- [x] Moscow
- [x] FTF
- [ ] Referencias bibliográficas
- [x] Histórico de versão

**Comment by caiooliv** [comment]
Não foi feito o FTF pois não houve necessidade.

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-priorizacao
