### ISSUE TITLE
[TS20] Contas no firebase sem cadastro no banco de dados.

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#161]
### Descrição:
Se por algum motivo ocorra um erro  no cadastro, como o serviço Api monitoria fora do ar, o cadastro é efetuado no firebase porém não persiste no banco de dados da aplicação, caso o cadastro não seja efetuado o cadastro no banco da aplicação, o firebase deve refletir essa ação.
### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Validação do cadastro no banco e no firebase.

 
### Comentários
Link para a [documentação do firebase](https://firebase.google.com/docs/web/setup)

**Comment by jpcirqueira** [comment]
A validação do usuário no banco deverá ser somente ao registrar um usuário?

**Comment by LucasSiqz** [comment]
não, a validação deve ser feita também ao realizar login.

**Comment by RCristyan** [comment]
Fizemos algumas alterações nos componentes Login e SignUp para tratar o problema do erro no cadastro. Agora quando o usuário é cadastrado apenas no Firebase e não no banco, é mostrada uma mensagem de que ocorreu um erro no registro e a conta dele é excluída imediatamente do Firebase. O usuário deve, então, tentar novamente e criar outra conta.

**Comment by caiooliv** [comment]
É necessário correções de bugs e feedback das informações. Ao encontrar o usuário no firebase e não no banco a mensagem está errada, atualmente ela está assim :
![image](https://user-images.githubusercontent.com/23109243/59647283-faa46600-9150-11e9-990c-633090f3b87f.png)
 é necessário mudanças para que seja mais agrádavel para o usuário como "Erro ao realizar operação, tente novamente". Além da correção de Bugs, quando o usuário é removido da base do firebase ao tentar cadastrar novamente a aplicação não permite, diz que o email está em uso

**Comment by jpcirqueira** [comment]
foram feitas mudanças consideráveis nas validações e foi corrigido o feedback para o usuário.
