### ISSUE TITLE
[TS21] Deploy contínuo ambiente de produção

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#163]
### Descrição:
Atualmente o produto não possui um deploy para o ambiente de produção, o que deve ser corrigido para o que o usuário final possa usar o sistema. Para isso é necessário a consolidação das etapas de build, testes e deploy no travis.
### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Deploy contínuo para ambiente de produção

**Comment by matheus-rn** [comment]
O Deploy contínuo para ambiente de produção foi implementado.
