### ISSUE TITLE
[DOC] EVM

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#166]
### Descrição:
Análise de valor agregado ou EVM é uma técnica de mensurar o desempenho.  No contexto da matéria se vê a importância de tal artefato para obter dados importantes para a entrega de valores.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Criação de tabelas.
- [x] Gráficos.

**Comment by LucasSiqz** [comment]
Tabelas e gráficos disponível em: https://docs.google.com/spreadsheets/d/1z9OSTJwVjdZhsARIMOXZu38xx6VbUyydPl3W9Jf82TI/edit?usp=sharing

**Comment by caiooliv** [comment]
A documentação do EVM estará disponível na [página de documentos](https://fga-eps-mds.github.io/2019.1-MaisMonitoria/) do projeto após a conclusão das sprints, visto que é necessário  o fim das mesmas para obter todos os dados relevantes.
