### ISSUE TITLE
[US29] Deletar monitoria

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#170]
### Descrição:
Quando um monitor desejar parar de ministrar a monitoria ele deve ser capaz de excluir a mesma, porém essa funcionalidade ainda não está implementada no front end, então deve se implementar para que somente o dono da monitoria possa fazer a exclusão dela. 

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Opção de excluir a monitoria no card expandido
- [x] Método de confirmação de exclusão de monitoria
- [x] Refatoração do card de monitoria no perfil, para excluir a partir do perfil

### Comentários
Para a confirmação da exclusão deve-se abrir uma modal perguntando se realmente deve ser feita a exclusão.

**Comment by lucasA27** [comment]
O que seria **método** de confirmação de exclusão de monitoria?

**Comment by caiooliv** [comment]
Como deletar monitoria é uma ação de risco, deve haver a confirmação que o usuário deseja excluir, como uma modal abrindo para perguntar se o usuário realmente deseja excluir a monitoria

**Comment by jpcirqueira** [comment]
Como pedido foi feito um dialogo com o usuário para que o usuário posso realmente excluir ou cancelar a operação.
