### ISSUE TITLE
[REFACTOR] Campos criar/editar monitoria 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#172]
### Motivo de refatoração:
Após os [testes de usabilidade](https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-teste-usabilidade-2.0) foi visto inconsistência  visuais em alguns campos de entrada, a refatoração deve ser feita para que os campos estejam padronizados e de acordo com a identidade visual da aplicação.

### Tópicos de aceitação:
- [x] Padronizar campos de entrada.

**Comment by RCristyan** [comment]
Através de pequenas alterações no componente EditMonitoring, foi possível padronizar os campos de forma que ficasse igual aos campos do componente RegisterMonitoring.

**Comment by LucasSiqz** [comment]
As duas telas agora estão consistentes, e foi escolhido a alteração no campo de descrição para obrigatório em ambos os casos,
