### ISSUE TITLE
[BUG] Multiplicação de likes/monitorias.

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#173]
### **Descreva o bug**
Após dar um like em uma monitoria, ou fazer a criação de uma nova monitoria se fizer o logout e o login novamente a monitoria que recebeu o like ganha mais um like com o usuário que fez o login, e a monitoria recém criada estará duplicada com o usuário que fez o login como dono da nova monitoria.

### **Para reproduzir o bug**
Passos para reproduzir-lo:
### Bug likes
1. Logue no +Monitoria.
2. Clique em uma monitoria no feed.
3. Clique no botão de like.
4. Faça logout
5. Faça Login
6. Clique na monitoria que recebeu o like no passo 3.
7. Entre na lista de likes.

### Bug monitoria
1. Logue no +Monitoria
2. Clique no botão de '+' para criar uma monitoria.
3. Preencha os campos da monitoria e crie a monitoria.
4. Faça logout
5. Faça login

### **Comportamento esperado**
Deveria os likes e as monitorias não deveriam ser multiplicados, somente existir se o houver a criação da monitoria ou se tiver dado o like. 
###  **Screenshots**
Se possível, adicione screenshots para ajudar a identificar e explicar o problema.

### **Desktop (complete as seguintes informações):**
 - OS: Linux
 - Browser Chrome
 - Version 74.0.3729.157

**Comment by lucasA27** [comment]
Para arrumar o bug foi feita ajustes nas validações para o usuário logado.
