### ISSUE TITLE
[BUG] Editar Perfil

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#174]
### **Descreva o bug**
Ao tentar editar o perfil o curso do usuário não está disposto na opção de curso, além disso  caso o usuário tente editar o perfil sem alterar a sua foto ele não consegui concluir a ação.
### **Para reproduzir o bug**
Passos para reproduzir-lo:
1. Logue na aplicação
2. Entre na aba de perfil.
3. Clique no botão de edição de perfil
4. Clique em confirmar edição
5. Veja o erro
### **Comportamento esperado**
É esperado que as edições sejam concluídas e que a foto não seja alterada, fique com a foto atual do usuário.

###  **Screenshots**
Se possível, adicione screenshots para ajudar a identificar e explicar o problema.

### **Desktop (complete as seguintes informações):**
 - OS: Linux
 - Browser Chrome
 - Version 74.0.3729.157

**Comment by LucasSiqz** [comment]
o bug foi resolvido, agora é possível editar o perfil corretamente, como sugestão de melhoria, sugiro ser possível excluir a foto atual e não apenas altera-la por outra.
