### ISSUE TITLE
[DOC] Postmortem

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#177]
### Descrição:
Ao final da disciplina de EPS/MDS é necessário refletir e escrever sobre os erros e as experiencias passados nas disciplinas, assim o documento de postmortem se torna uma tarefa essencial para a disciplina.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Criação do documento de postmortem

### Comentários
Link para página de [documentos do +Monitoria](https://fga-eps-mds.github.io/2019.1-MaisMonitoria/)

**Comment by LucasSiqz** [comment]
disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-postmortem
