### ISSUE TITLE
[DOC] Lançar release notes

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#178]
### Descrição:
É necessário os lançamentos dos releases notes.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Features
- [x] Bugs resolvidos
- [x] O que está por vir

**Comment by LucasSiqz** [comment]
Nova release disponível em : https://github.com/fga-eps-mds/2019.1-MaisMonitoria/releases
