### ISSUE TITLE
[DOC] Preparação para R2

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#180]
### Descrição:
Ao final das matérias de EPS/MDS é necessário que os membros se preparem para a apresentação final do projeto.

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Brainstorm para apresentação.
 
- [x] Correção do deploy
- [x] Slides de apresentação

**Comment by LucasSiqz** [comment]
O brainstorm aconteceu presencialmente na FGA em 20/06/2019, contou com a presença de todos os membros, exceto o Lucas Alexandre.

Aspectos levantados:

Sugestões:
* mostrar o que a gnt corrigiu da r1 pra r2
* software pode ser levado para outras faculdades
* dizer os pontos fortes do produto
* tentar seguir um modelo de apresentação de produto existente
* detalhar o problema e mostrar a solução
* mostrar a parte da gerencia do projeto
* falar da escolha do pwa
* foco no processo, metodolgia, ritos, crescimento e amadurecimento da equipe.

Pontos positivos do produto
+ PWA x4
+ Telas bem intuitivas, boa usabilidade x3
+ Catalago e pesquisa de monitoria x2
+ Solução quanto a disponibilidade de novas monitorias x2
+ Integração com o telegram
+ Potabilidade x2
+ Mais flexibilidade e desing mais moderno em relação a outros apps semelhantes

Pontos negativos do produto
- Apenas um meio de comunicação x4
- Pesquisa limitada x2
- Não ter números de curtidas no card minimizado
- Não existir interfaces adaptadas para telas do pc e do celular
- Login apenas por email e senha x2
- Design e padronização do app
