### ISSUE TITLE
[REFACTOR] Refatorar GitHub Pages

### ISSUE THREAD

**Issue by lukassxp** [fga-eps-mds/2019.1-MaisMonitoria#23]
### Motivo de refatoração:
O github pages não está visualmente agradável e estrutura de pastas não atendiam os critérios de aceitação. 

### Tópicos de aceitação:
- [x] Estruturas de pastas
- [x] Integração/Deploy contínuo. 
- [x] Docker
- [x] Visual agradável.

**Comment by lukassxp** [comment]
A estrutura de pastas foi arrumada, o docker está configurado, basta rodar um docker-compose up e a integração/deploy contínuos estão operando, sendo que a integração é feita a cada commit e o deploy a cada novo commit na master que altera algo no GitHub Pages.

**Comment by lukassxp** [comment]
Foi utilizada parte de um template gratuito encontrado na web como layout da nossa página inicial, os textos e imagens de apresentação do produto não foram inseridos pois essa é uma atribuição do Product Owner ficando a cargo dele posteriormente popular nossa Home Page com conteúdo voltado para o nosso produto. Com isso considero a issue concluída e aguardo revisão dos demais membros do grupo.

**Comment by LucasSiqz** [comment]
Concordo que a elaboração da pagina inicial deve ser uma tarefa do Product Owner, em relação a refatoração, o projeto está mais organizado, docker está funcionando e a aplicação do template melhorou o visual.
