### ISSUE TITLE
[REFACTOR] Realizar revisão textual e de conteúdo dos documentos 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#42]
### Motivo de refatoração:
Maioria dos documentos apresenta erros gramaticais, de estruturação dos documento e falta de tópicos.
### Tópicos de aceitação:
- [x] Descrição de metodologia
- [x] Documento de arquitetura
- [x] Folha de de estilo
- [x] Introspecção
- [x] NFR
- [x] Observação
- [x] Prototipação
- [x] Richpicture
- [x] TAP
- [x] Teste de usabilidade
- [x] Documento de visão
- [x] Plano de custos
- [x] Plano de GCS 
- [x] Plano de GRH
- [x] Plano de riscos
- [x] Documentação das sprints
- [x] Plano de tempo

### Comentários.
Para a issue ser concluída deve ser feita a revisão em todos os doc listados acima.

**Comment by LucasSiqz** [comment]
Foi feito a revisão de todos os documentos, inclusive os que foram feito ao decorrer dessa sprint. Também foi feito a rastreabilidade dos requisitos nos documentos, levando em consideração as features definidas no backlog.
