### ISSUE TITLE
[DOC] Plano de medição 

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#43]
### Descrição:
Deve ser definido um plano de medição, para a definição das métricas de qualidade.
### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Introdução
- [x] Objetivo
- [x] Questões
- [x] Métricas
- [x] Referências
- [x] Histórico de revisão

**Comment by LucasSiqz** [comment]
Disponível em: https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-plano-medicao
