### ISSUE TITLE
[TS10] Avaliação técnica da autenticação

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#45]
### Descrição:
Avaliação das opções de autenticação via API externa, para definir a que melhor se encaixa no contexto do produto.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Definir tecnologia a ser usada.
- [x] Avaliar API do facebook.
- [x] Avaliar API do Google
- [x] Verificar outras opções
 
### Comentários
[API facebook](https://developers.facebook.com/docs/facebook-login/)
[API google](https://developers.google.com/adwords/api/docs/guides/authentication?hl=pt-br)

**Comment by RCristyan** [comment]
Fizemos algumas pesquisas e avaliamos as diferentes alternativas para realizar a autenticação. Por enquanto a principal escolha é o serviço do Facebook, cujos detalhes estão disponíveis em: https://developers.facebook.com/docs/facebook-login/auth-vs-data
Agora resta a aprovação dos membros de EPS

**Comment by matheus-rn** [comment]
**Relato da atividade:**

Durante a sprint o devOps(eu), o arquiteto e um membro de MDS procuraram definir o modo como a autenticação do usuário seria realizada. No sábado houve uma reunião com toda a equipe onde foram discutidos alguns aspectos referentes ao assunto. Buscando diminuir o escopo, foram verificados opções onde a autenticação pudesse ser realizada sem a criação de um novo serviço, partindo da ideia de usar APIs externas. Dentre as diversas APis analisadas, ficou decidido que será utilizada a API do Facebook, para o trabalho de autenticação.

**Comment by lukassxp** [comment]
Durante a realização da #56 tomamos conhecimento do [firebase](https://firebase.google.com/docs) que além de nos facilitar realizar autenticação por meio do facebook fornece inúmeras outras maneiras de se realizar autenticação, por isso foi decidido pela equipe de EPS utilizar o [firebase](https://firebase.google.com/docs) como ferramenta de autenticação externa.
