### ISSUE TITLE
[TS06] Modelagem da estrutura de classes e bancos de dados de usuário

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#46]
### Descrição:
Realizar a modelagem das classes e do banco de dados para que possa atender a necessidades do controle dos dados de usuários.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Construir diagrama de classes.
- [x] Definir relação entre tabelas do banco de dados.

 
### Comentários
Exemplo de [diagrama de classes](https://github.com/2018-2-Desenho/CabecaVoleiJoelhoPe/wiki/Diagramas-de-Classe)

**Comment by MoacirMSJ** [comment]
Primeira versão do diagrama de classes está disponível em: https://drive.google.com/drive/folders/18LNvrzrv8HmDT-B7FrIzIdmEz7rE-4uV

**Comment by lukassxp** [comment]
**Relato da atividade:**

Durante a sprint o arquiteto(eu) se reuniu com os dois membros de MDS designados para a issue algumas vezes e primeiramente conversou sobre modelagem e banco de dados para que eles entendessem sobre oq se trata a issue, logo após foram passadas orientações pra se iniciar a atividade. A dinâmica da realização da atividade se deu da seguinte forma:

- MDS apresentava uma modelagem.
- O arquiteto fazia observações e sugestões.
- MDS refazia a modelagem.

Esse ciclo se repetiu até que o arquiteto considerou que a modelagem estava num bom nível e que ela já podia ser apresentada para o resto da equipe. 

No sábado houve uma reunião com toda a equipe onde os membros de MDS apresentaram a modelagem para o grupo, surgiram mais algumas sugestões e foram sanadas algumas pequenas duvidas que restavam, após a apresentação foram feitos os ajustes sugeridos pela equipe e com aval de todos a modelagem foi aceita.

**Obs:** 

- Foram adiantadas algumas atividades de outras issues como um esboço da modelagem das monitorias e um começo de implementação para verificar a real viabilidade da modelagem proposta.

- Após ser realizada a implementação total da modelagem vai ser solicitado a equipe de MDS refazer o diagrama de classes para que ele se adeque a estrutura do Django Rest.

**A issue foi considerada concluída pela equipe de EPS!**
