### ISSUE TITLE
[TS12] Gerenciamento de requisição

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#55]
### Descrição:
É necessário que as requisições sejam gerenciadas a partir de um único ponto.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Gerenciamento das requisições de monitoria.
- [x] Gerenciamento das requisições da autenticação.

**Comment by matheus-rn** [comment]
Foi implementado a estrutura de gerenciamento de requisições, mediadas pela api gateway, onde o token será verificado e a requisição para a api monitoria será realizada.
