### ISSUE TITLE
[US08] Disponibilizar Autenticação por API Externa

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#56]
### Descrição:
Deve autenticar as contas utilizando meu cadastro de outro serviço, por meio de API externa.
### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Ter acesso as informações da conta do usuário no firebase.
- [x] Estabelecer regra de negocio de armazenamento e acesso ao token.

### Comentários
Link para API do facebook se encontra disponível [aqui](https://developers.facebook.com/docs/facebook-login/)

**Comment by lukassxp** [comment]
Para auxiliar no cadastro e autenticação dos usuários da aplicação utilizamos o [Firebase](https://firebase.google.com/?gclid=Cj0KCQjwnpXmBRDUARIsAEo71tT7sUN-Nk3chAxGDYk2UQPMjt_UySeE3EICERZ8TVGJJi9Cz4wtXicaAgN3EALw_wcB). A integração com a autenticação externa aconteceu em dois pontos, na interface do usuário cuidando da autenticação e cadastro no firebase, e na api gateway realizando verificação por token para dar acesso as requisições nos microsserviços.
