### ISSUE TITLE
[DOC] Pipeline DevOps

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#62]
### Descrição:
Desenvolver o pipeline do DevOps, para que entregas e atualizações sempre estejam com maior tolerância a falhas. 

### Tópicos do documento
Lista de tópicos para serem realizadas. 

- [x] Gitflow.
- [x] Pipeline de integração contínua.
- [x] Pipeline de deploy contínua.

**Comment by LucasSiqz** [comment]
Faltou adicionar o codecov no pipeline do ambiente de develop.

**Comment by matheus-rn** [comment]
Foi ajustado o pipeline referente ao pr na develop.
