### ISSUE TITLE
[REFACTOR] Integração Front-end com Back-end

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#70]
### Motivo de refatoração:
A refatoração deve ser feita para que o front-end esteja preparado para receber os dados da API.

### Tópicos de aceitação:

- [x] Usar dados providos da API no front-end.

**Comment by caiooliv** [comment]
Os dados vindos da API estão sendo utilizados no frontend

**Comment by LucasSiqz** [comment]
Revisado e aprovado, visto que já é possível enviar e receber dados no frontend.
