### ISSUE TITLE
[REFACTOR] Testar API  Gateway

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#71]
### Motivo de refatoração:
A API deve ter os testes unitários, para garantir o funcionamento do código.

### Tópicos de aceitação:
- [x] Mínimo de 70% de cobertura do código.

### Comentários.
Documentação do pyteste disponível em : [Link](https://docs.pytest.org/en/latest/)

**Comment by MatheusEstanislau** [comment]
Realizado cobertura de 85% nos testes das funcionalidades da api Gateway, utilizando APITestCase, ferramenta de testes padrão do DjangoRestFramework .

**Comment by caiooliv** [comment]
Foi realizada a cobertura mínima para o fechamento da issue.
![Cobertura](https://uploaddeimagens.com.br/images/002/072/596/original/Captura_de_tela_de_2019-04-28_21-50-08.png?1556499146)
