### ISSUE TITLE
[REFACTOR] Testar API monitoria

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#72]
### Motivo de refatoração:
A API deve ter os testes unitários, para garantir o funcionamento do código.

### Tópicos de aceitação:
- [ ] Mínimo de 70% de cobertura do código.

### Comentários.
Documentação do pyteste disponível em : [Link](https://docs.pytest.org/en/latest/)

**Comment by jpcirqueira** [comment]
como nos não alteramos nada da implementação do Framework, foi notado que a cobertura do teste já estava conforme o esperado.
