### ISSUE TITLE
[REFACTOR] Testar Front-end

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#73]
### Motivo de refatoração:
A API deve ter os testes unitários, para garantir o funcionamento do código.

### Tópicos de aceitação:
- [x] Mínimo de 70% de cobertura do código.

### Comentários.
Documentação do enzyme disponível em : [Link](https://github.com/airbnb/enzyme)

**Comment by lucasA27** [comment]
Os testes foram feitos usando Jest e enzyme à partir de snapshots e conseguimos alcançar a cobertura de 81% de linhas testadas.

**Comment by caiooliv** [comment]
A cobertura de teste atingiu o valor mínimo requerido pela issue.
![Imagem](https://uploaddeimagens.com.br/images/002/070/304/full/Captura_de_tela_de_2019-04-27_13-25-50.png?1556382375)
