### ISSUE TITLE
[TS16] Finalizar Pipeline

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#74]
### Descrição:
Finalizar o pipeline para 

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Realizar deploy no ambiente de homologação.

**Comment by matheus-rn** [comment]
Não foi possível fechar a issue, visto que houve alguns problemas relacionados a configuração do rancher.

**Comment by matheus-rn** [comment]
Devido a alteração da data do termino da sprint, e com a ajuda de colegas, foi possível configurar o rancher para o deploy no ambiente de homologação.
