### ISSUE TITLE
[DOC] Preparação para R1

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#75]
### Descrição:
Preparar material de apresentação para R1

### Tópicos do documento

- [x] Slid de apresentação
- [x] Refatoração de documentos
- [x] Treinar equipe de MDS para apresentação 

### Comentários
Os critérios de aceitação da issue estão descritos acima.

**Comment by LucasSiqz** [comment]
Como preparação para a release 1 também esta sendo feita a refatoração de alguns documentos

**Comment by LucasSiqz** [comment]
Para o documento de arquitetura as refatorações a serem feitas são: 

2 - Representação Arquitetural
- Arquitetura Cliente / Servidor
- Arquitetura Microsserviços
- MVC
- Django
- Explicar Django Rest
- React
- Autenticação Firebase
- Corrigir Diagrama de Relações

3 - Backlog
- Substituir historias de usuário por epicos
- Escrever textos informando que tem mais detalhes no backlog.

Arquitetura de microsserviços

5 - Visão Arquiteturais
- Visão Logica
	- Diagrama de classes (Limpar o diagrama e representar apenas os modelos)
- Visão de Implantação
	- Diagrama de implantação
	- Autenticação
- Visão de Implementação
	- Falar sobre as classes serialize e viewsetting (Parte que foi retirada do diagrama de classes)
	- Falar sobre os componentes do react
8 - Pipeline
	- Refatorar diagrama
	- Adicionar descrição informativa
	- Falar sobre o resolução do gargalo que a gateway pode causar por ser uma facade(Encaixa melhor como Bridge)

**Comment by LucasSiqz** [comment]
Nos planos as refatorações a serem feitas são:
Custos
- Adicionar gastos com deploy
	- Aluguel de maquina na DO
	- Compra de Dominio

GCS
- Ajustar politicas de commit dos outros repositorios
- Melhorar politicas de branch
- Descrever melhor as politicas de aceitação de codigo
- Descrição detalhada do pipeline e das ferramentas

GHR
- Conclusão R1

Plano de tempo
- Revisar backlog
- Refatorar roadmap

Plano de medição
- Revisar metricas

**Comment by caiooliv** [comment]
A issue ficará aberta até o dia da apresentação da Release 01 (02/05/2019), pois a preparação é necessária até o momento da entrega.

**Comment by LucasSiqz** [comment]
o [Backlog](https://fga-eps-mds.github.io/2019.1-MaisMonitoria/docs/doc-backlog) foi dividido em: backlog do produto e backlog do projeto.

**Comment by MoacirMSJ** [comment]
**Documento de Visão**

Foram refatorados os tópicos:   

- Objetivo
- Descrição do usuário
- Visão geral
- Recursos do produto
- Requisitos Não Funcionais

Foram adicionados novos tópicos:

- Descrição do problema
- Instrução de posição do produto
- Restrições
