### ISSUE TITLE
[DOC] Lançar Release Notes

### ISSUE THREAD

**Issue by caiooliv** [fga-eps-mds/2019.1-MaisMonitoria#76]
### Descrição:
Foi planejado a disponibilização  de um pré-release notes ao fim da sprint 9.

### Tópicos do documento
- [x]  Features
- [x]  Bugs resolvidos
- [x]  O que está por vir

**Comment by LucasSiqz** [comment]
utilizaremos como modelo as releases do repositório do cypress: https://github.com/cypress-io/cypress/releases

**Comment by LucasSiqz** [comment]
disponível em: https://github.com/fga-eps-mds/2019.1-MaisMonitoria/releases/tag/v0.1.0

**Comment by LucasSiqz** [comment]
Foram adicionados também informações acerca da documentação do +Monitoria.

**Comment by lukassxp** [comment]
A issue não está bem descrita, no entanto os critérios de aceitação foram feitos e o release notes está de acordo com o planejado.
